S05 us108 implement 30 days limit for ideas
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #111
Opened 2023-07-10 09:34 UTC by StoicFrenchDev

2023-07-10 09:39 UTC, Spolito24 approved these changes

2023-07-10 10:13 UTC, AurelOconnell approved these changes

2023-07-10 13:52 UTC, aldaitzwild requested changes

2023-07-10 13:52 UTC, aldaitzwild commented on src/Command/ArchiveIdeasCommand.php
> +            }
Do not compare formatted Date, just compare Date.
Cause when you compare two string : 
2023-5-2 > 2023-5-10

2023-07-10 14:33 UTC, aldaitzwild requested changes

2023-07-10 14:33 UTC, aldaitzwild commented on src/Service/GetIdeaRemainingDays.php
> +class GetIdeaRemainingDays extends AbstractController
Why does a Service inherit from AbstractController ?

2023-07-10 14:38 UTC, aldaitzwild requested changes

2023-07-10 14:38 UTC, aldaitzwild commented on src/Service/GetIdeaRemainingDays.php
> +    }
You should have this in your entity

2023-07-10 14:55 UTC, aldaitzwild requested changes

2023-07-10 14:55 UTC, aldaitzwild commented on src/Entity/Idea.php
> +        $endDate = $idea->getEndDate();
do you really need an idea here ? IN an idea ?? Couldn't $this wouldn't be enough ?

2023-07-10 15:05 UTC, aldaitzwild requested changes

2023-07-10 15:05 UTC, aldaitzwild commented on src/Controller/IdeaController.php
> +            'daysRemaining' => $daysRemaining,
As you already pass the idea to twig, you don't need to pass your getRemainingDays, you can call it directly from twig

2023-07-11 09:25 UTC, aldaitzwild approved these changes

2023-07-11 09:25 UTC, merged