S06 us105 show the create slack button only when enough supporter
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #113
Opened 2023-07-10 12:11 UTC by Spolito24

2023-07-10 12:26 UTC, StoicFrenchDev approved these changes

2023-07-10 13:56 UTC, aldaitzwild requested changes

2023-07-10 13:56 UTC, aldaitzwild commented on src/Service/IdeaSupporter.php
> +    }
This should be in the Idea entity

2023-07-10 14:34 UTC, aldaitzwild requested changes
Code Quality checks failed : 

Error: Parameter $ideaSupporter of method App\Controller\SlackController::createChannel() has invalid type App\Service\IdeaSupporter.
Error: Call to method isChannelCreatable() on an unknown class App\Service\IdeaSupporter.
 ------ --------------------------------------------------------------------- 
  Line   Controller/SlackController.php                                       
 ------ --------------------------------------------------------------------- 
  30     Parameter $ideaSupporter of method                                   
         App\Controller\SlackController::createChannel() has invalid type     
         App\Service\IdeaSupporter.                                           
  41     Call to method isChannelCreatable() on an unknown class              
         App\Service\IdeaSupporter.                                           
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ ---------------------------------------------------------------------

2023-07-10 14:58 UTC, aldaitzwild requested changes

2023-07-10 14:58 UTC, aldaitzwild commented on src/Controller/IdeaController.php
> +            'supporterNeeded' => $supporterNeeded,
You already pass the idea to twig, why do you need to send these methods ? You can call them directly from twig

2023-07-11 09:26 UTC, aldaitzwild approved these changes

2023-07-11 12:13 UTC, aldaitzwild approved these changes

2023-07-11 12:13 UTC, merged