S06 us109 progress bar
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #118
Opened 2023-07-11 13:09 UTC by Spolito24

2023-07-11 13:29 UTC, AurelOconnell approved these changes

2023-07-11 14:21 UTC, StoicFrenchDev approved these changes

2023-07-11 14:36 UTC, aldaitzwild requested changes

2023-07-11 14:36 UTC, aldaitzwild commented on templates/loginBase.html.twig
> +    {% endfor %}
Why did you remove a good indentation ?

2023-07-12 09:58 UTC, aldaitzwild approved these changes

2023-07-12 09:58 UTC, merged