Fix update entities asserts
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #138
Opened 2023-07-17 13:30 UTC by StoicFrenchDev

2023-07-17 13:41 UTC, AurelOconnell approved these changes

2023-07-17 14:07 UTC, aldaitzwild requested changes

2023-07-17 14:07 UTC, aldaitzwild commented on src/Controller/PasswordController.php
> +        if (!empty($newPassword) && strlen($newPassword) > 6) {
Ok and if the password length is exactly 6, what does happen ?

2023-07-17 15:27 UTC, aldaitzwild requested changes

2023-07-17 15:27 UTC, aldaitzwild commented on src/Controller/PasswordController.php
> +        if (!empty($newPassword) && strlen($newPassword) >= 7) {
The suspens is unbearable ! What happens when you have a password with EXACTLY 6 characters !!!!?????

2023-07-17 15:30 UTC, benrcd commented on src/Controller/PasswordController.php
> +        if (!empty($newPassword) && strlen($newPassword) >= 7) {
WHATS IN THE BOX ?!????!!??

2023-07-18 06:56 UTC, aldaitzwild approved these changes

2023-07-18 06:56 UTC, merged