the idea date are only for the last 6 month
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #140
Opened 2023-07-17 14:05 UTC by Spolito24

2023-07-17 14:31 UTC, StoicFrenchDev approved these changes

2023-07-17 15:56 UTC, aldaitzwild requested changes

2023-07-17 15:56 UTC, aldaitzwild commented on templates/admin/ideas.html.twig
> +                                    <p>Êtes-vous sûr de vouloir Archiver l'idée : <br><b>{{idea.id}} - {{idea.title}}</b><br> (vous pourrez toujours la
No `<br>` allowed

2023-07-17 15:56 UTC, aldaitzwild commented on templates/idea/show.html.twig
> +                                    <p>Êtes-vous sûr de vouloir Archiver l'idée : <br><b>{{idea.id}} - {{idea.title}}</b><br> (vous pourrez toujours la
No `<br>` allowed

2023-07-18 10:12 UTC, aldaitzwild approved these changes

2023-07-18 10:12 UTC, merged