S07 us141 new idea redirect to new show
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #142
Opened 2023-07-17 15:13 UTC by Spolito24

2023-07-17 15:15 UTC, AurelOconnell approved these changes

2023-07-18 06:59 UTC, aldaitzwild requested changes

2023-07-18 06:59 UTC, aldaitzwild commented on templates/admin/ideas.html.twig
> +                                    <p>Êtes-vous sûr de vouloir Archiver l'idée : <br><b>{{idea.id}} - {{idea.title}}</b><br> (vous pourrez toujours la
Still no `<br>` allowed

2023-07-18 06:59 UTC, aldaitzwild commented on templates/idea/show.html.twig
> +                                    <p>Êtes-vous sûr de vouloir Archiver l'idée : <br><b>{{idea.id}} - {{idea.title}}</b><br> (vous pourrez toujours la
Still no `<br>` allowed

2023-07-18 10:12 UTC, aldaitzwild approved these changes

2023-07-18 10:12 UTC, merged