Display categories on sideBar
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #25
Opened 2023-06-07 13:41 UTC by StoicFrenchDev

A global methode was created to provide the sideBar with categories all the time.
A collapse menu is used to display said categories.

2023-06-07 14:14 UTC, Spolito24 approved these changes, later dismissed

2023-06-07 14:26 UTC, aldaitzwild requested changes

2023-06-07 14:26 UTC, aldaitzwild commented on templates/component/_sideNavbar.html.twig
> +                        {% endfor %}
I don't understand what you intend to show here. Do you realize that you load in global and show here ALL the ideas of your database. If you have 5000 ideas, there will be 5000 cards here ...

2023-06-07 14:48 UTC, StoicFrenchDev commented
The function $getPerimeters was replaced by the function $getDistinctPerimeters so the displayed list won't be filled with clone, only the ones available in the idea form.

2023-06-07 14:54 UTC, aldaitzwild requested changes

2023-06-07 14:54 UTC, aldaitzwild commented on templates/component/_sideNavbar.html.twig
> +                        <div class="card"><a class="dropdown-item" href="#">{{perimeter.perimeter}}</a>
Better ! But still too much. You don't need to get here full Idea objects. getDistinctPerimeters should return an array of string, not an array of ideas

2023-06-07 15:18 UTC, StoicFrenchDev commented
The function getDistinctPerimeters focus now on the strings corresponding to the differents 'perimeter' instead of using the whole object all the time. It should be lighter and straight to the point

2023-06-08 07:00 UTC, AurelOconnell approved these changes
it seems fine to me, shorter and lighter, array_map returns only $result from array perimeter. But as I said before, difficult for me to be really sure about the whole thing

2023-06-08 07:09 UTC, aldaitzwild approved these changes

2023-06-08 07:09 UTC, merged