S02 us36 profil page
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #48
Opened 2023-06-15 18:24 UTC by Spolito24

2023-06-15 20:04 UTC, AurelOconnell approved these changes
maybe extend the guessextension to others ? But jpg png & jpeg are the most common. It's only fonctional, not technical

2023-06-16 06:22 UTC, aldaitzwild requested changes

2023-06-16 06:22 UTC, aldaitzwild commented on src/Controller/UserController.php
> +use App\Service\ImageFileVerification;
This use seems coming from nowhere

2023-06-16 06:48 UTC, aldaitzwild approved these changes

2023-06-16 06:48 UTC, merged