49 idea stickers agency service
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #50
Opened 2023-06-17 15:20 UTC by AurelOconnell

2023-06-17 16:36 UTC, Spolito24 approved these changes

2023-06-18 14:35 UTC, StoicFrenchDev requested changes
We need to add the "orderBy" regarding the publication date on both queries.

2023-06-18 15:09 UTC, StoicFrenchDev approved these changes

2023-06-19 06:55 UTC, aldaitzwild approved these changes

2023-06-19 06:55 UTC, merged