S03 users can delete their ideas
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #76
Opened 2023-06-21 15:19 UTC by StoicFrenchDev

2023-06-21 15:29 UTC, AurelOconnell approved these changes

2023-06-23 07:35 UTC, aldaitzwild requested changes

2023-06-23 07:35 UTC, aldaitzwild commented on templates/home/index.html.twig
> +                        <h2 class="card-title fs-2">{{ idea.title|u.truncate(16, '...', false) }}</h3>
No ! a `</h3>` won't close a `<h2>`

2023-06-23 07:58 UTC, aldaitzwild approved these changes

2023-06-23 07:58 UTC, merged