S04 us84 slack button on idea pages
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #91
Opened 2023-06-26 14:25 UTC by AurelOconnell

2023-06-26 14:50 UTC, Spolito24 approved these changes

2023-06-27 07:36 UTC, StoicFrenchDev requested changes
style="
                            align-items: center;
                            color: #fff;
                            background-color: #4a154b;
                            border: 0;
                            border-radius: 4px;
                            display: inline-flex;
                            font-family: Lato, sans-serif;
                            font-size: 16px;
                            font-weight: 600;
                            height: 48px;
                            justify-content: center;
                            text-decoration: none;
                            width: 100%;
                        "

The CSS should be in the SCSS file

2023-06-27 09:44 UTC, AurelOconnell commented
Need to show this button for author's idea only :)

2023-06-27 11:46 UTC, Spolito24 approved these changes

2023-06-27 12:15 UTC, aldaitzwild requested changes

2023-06-27 12:15 UTC, aldaitzwild commented on ngrok.exe
No .exe should be versionned in git. It's not a part of your code

2023-06-27 13:42 UTC, aldaitzwild requested changes

2023-06-27 13:42 UTC, aldaitzwild commented on ngrok.exe
Still in the PR

2023-07-03 10:06 UTC, aldaitzwild approved these changes

2023-07-03 10:08 UTC, merged