S04 us85 channel creation linked to idea name
WildCodeSchool/0322_P3_Php_Lyon_Salesforce pull request #96
Opened 2023-07-03 10:30 UTC by AurelOconnell

2023-07-03 12:42 UTC, Spolito24 approved these changes

2023-07-03 14:18 UTC, aldaitzwild requested changes

2023-07-03 14:18 UTC, aldaitzwild commented on src/Controller/SlackController.php
> +        $slugger = new AsciiSlugger(); // Create a new instance of the AsciiSlugger
No ! Use a SluggerInterface as showed in the documentation : https://symfony.com/doc/current/components/string.html#slugger

2023-07-04 10:27 UTC, aldaitzwild approved these changes

2023-07-04 12:32 UTC, merged